"""
FastAPI application for serving the fine‑tuned DistilBERT sentiment
classifier.  This API exposes a single POST endpoint at `/predict` that
accepts a JSON payload with a movie review and returns the predicted
sentiment along with the model's confidence.

Usage:

1. Ensure that the directory ``distilbert-imdb-best/`` contains a fine‑tuned
   DistilBERT model (as created by running ``imdb_sentiment_classifier.py``).
2. Install dependencies: ``fastapi``, ``uvicorn``, ``transformers``, and ``torch``.
3. Run the server with ``uvicorn app:app --host 0.0.0.0 --port 8000``.
4. Navigate to ``http://localhost:8000/docs`` to explore the interactive API
   documentation automatically generated by FastAPI.

Example request::

    curl -X POST -H "Content-Type: application/json" \
         -d '{"review": "I loved this movie!"}' \
         http://localhost:8000/predict

Response::

    {
      "sentiment": "positive",
      "confidence": 0.9972
    }
"""
import os
from typing import Dict
from fastapi import FastAPI
from pydantic import BaseModel, Field
from typing import Literal
import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from typing import Optional

class ReviewRequest(BaseModel):
    """Schema for incoming prediction requests."""
    review: str


class PredictionResponse(BaseModel):
    sentiment: Literal["positive", "negative"]
    confidence: float = Field(ge=0.0, le=1.0)

def load_model(model_dir: Optional[str] = None):
    """Load a fine‑tuned DistilBERT model and its tokenizer.

        Parameters
        ----------
        model_dir : str
            Directory containing the model and tokenizer files.
        Returns
        -------
        model : AutoModelForSequenceClassification
            The loaded PyTorch model.
        tokenizer : AutoTokenizer
            Tokenizer corresponding to the model.
        """
    model_dir = model_dir or os.environ.get("MODEL_DIR", "distilbert-imdb-best")
    tokenizer = AutoTokenizer.from_pretrained(model_dir)
    model = AutoModelForSequenceClassification.from_pretrained(model_dir)
    model.eval()
    return model, tokenizer


model, tokenizer = load_model()

app = FastAPI(
    title="IMDB Sentiment Analysis API",
    description=(
        "Classify movie reviews as positive or negative using a fine‑tuned"
        " DistilBERT model. Submit a review in the request body as JSON and"
        " receive the predicted sentiment and confidence score."
    ),
    version="1.0.0",
)


@app.get("/")
def read_root() -> Dict[str, str]:
    """Health check endpoint."""
    return {"message": "IMDB Sentiment Analysis API is running."}


@app.post("/predict", response_model=PredictionResponse)
def predict_sentiment(request: ReviewRequest) -> PredictionResponse:

    encoded = tokenizer(request.review, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**encoded)
        probs = F.softmax(outputs.logits, dim=1)[0]
        confidence, pred_class = torch.max(probs, dim=0)

    sentiment = "positive" if pred_class.item() == 1 else "negative"
    return PredictionResponse(sentiment=sentiment, confidence=float(confidence.item()))